.gitignore

gitignore, 메인 추가

---

Semi/.settings/org.eclipse.core.resources.prefs
Semi/WebContent/plan/timetable/test_search01.jsp
Semi/WebContent/plan/timetable/timetable.jsp
Semi/WebContent/resources/timetable/fullcalendar/fullcalendar.js

캘린더에 구글 검색 api 넣어놓고, 끌어서 드롭까지는 가능( 검색 결과 하나만 뜨는게 문제)
+ 구글 검색 api 같이 보는중 (재우오빠 파트)

1017 - 구글 검색api 테스트 및 캘린더쪽 연동(진행중) - 해진

---

Semi/WebContent/plan/story/mini/storyView.jsp
Semi/WebContent/plan/timetable/minViewModalTest.jsp

10/17
miniVeiwModalTest추가
- 상지

miniViewModalTest 추가

---

.gitignore
Semi/build/.gitignore

build 폴더 안에 있던 gitignore 파일 없애고, Semi 밖에 있는 파일에는 ' /Semi/build/' (원래 있던 내용, 아까 잠깐 지웟었음) 다시 작성해서 넣어놓음

1017 - gitignore 파일 다시 올림

---

Semi/src/dao/story/StoryDao.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/dto/plan/Plan.java
Semi/src/dto/story/Story.java

Dto : 
1. Plan -> String bannerURL 멤버필드 추가
2. Story -> file_idx 멤버필드 삭제
StoryDao
1. SelectStoryidx 메소드 추가 : 스토리의 현재 인덱스 불러오는 메소드 
- 상지 -

10/18 Dto : Plan,Story 수정, StoryDao 스토리의 인덱스 불러오는 메소드 추가

---

Semi/WebContent/plan/story/storyView.jsp
Semi/src/controller/story/StoryViewController.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/dto/story/Comment.java
Semi/src/dto/story/Story.java
Semi/src/service/stroy/StoryService.java
Semi/src/service/stroy/StoryServiceImpl.java
Semi/src/utils/CalcDate.java

10/19 - 상지
calcDate-calcPriod -기간계산하는 함수 추가, 플랜당 스토리 불러오기 테스트중

calcDate-calcPriod -기간계산하는 함수 추가, 플랜당 스토리 불러오기 테스트중

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/main/main.jsp
Semi/WebContent/user/join.jsp
Semi/WebContent/user/login.jsp
Semi/src/controller/user/UserDeleteController.java
Semi/src/controller/user/UserJoinController.java
Semi/src/controller/user/UserLoginController.java
Semi/src/controller/user/UserSocialLoginController.java
Semi/src/dao/user/UserDao.java
Semi/src/dao/user/UserDaoImpl.java
Semi/src/dto/user/User.java
Semi/src/service/user/UserService.java
Semi/src/service/user/UserServiceImpl.java

1. 카카오톡 소셜로그인 - jsp에서 서블릿으로 유저 정보 파라미터 전달하는 코드 작성
2. userdaoimpl 에서 insert 메소드 수정
3. userdaoimpl 에서 checkid() 코드 작성
4. 헤더윗메뉴에서 제이쿼리 추가 코드 하나 더 있길래 삭제함
5. 여러 파일에서 단어 email을 id로 바꿈
6. userService에 social 로그인 처리하는 함수 추가
7. userSocialController에 로그인처리, 세션저장 코드 추가

1018 지은 - 카카오톡 소셜로그인

---

Semi/WebContent/plan/story/storyDetailView.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/src/controller/story/StoryViewController.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/dto/story/Story.java

2018/10/20
상지
STORY 읽기 쪽 테스트중~

2018/10/20 story 읽어오는 기능 개발중!

---

Semi/WebContent/user/update.jsp

1021 지은 회원수정페이지 수정

---

Semi/WebContent/user/login.jsp
Semi/WebContent/user/myPage.jsp
Semi/WebContent/user/update.jsp
Semi/src/controller/user/UserLoginController.java
Semi/src/controller/user/UserSocialLoginController.java
Semi/src/controller/user/UserUpdateController.java
Semi/src/dao/user/UserDao.java
Semi/src/dao/user/UserDaoImpl.java
Semi/src/service/user/UserService.java
Semi/src/service/user/UserServiceImpl.java

1. 소셜로그인한 회원과 아이디로 로그인한 회원별로 회원수정 페이지 다르게 보이게 수정(myPage.jsp, update.jsp)
2. 로그인 컨트롤러, 소셜로그인 컨트롤러에 세션 유지 시간 설정 추가
3. 회원정보수정 시 유저서비스에서 파라미터 얻어오는 메소드 새로 추가
4. 소셜로그인 컨트롤러에서 유저 정보를 세션에 저장할때(setAttribute) 저장 이름이 로그인컨트롤러와 겹쳐서
"socialUser"로 이름 변경

1022 지은 회원정보수정 페이지 수정

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/timetable/map02.jsp
Semi/WebContent/plan/timetable/timetable_postTest.jsp
Semi/WebContent/plan/timetable/timetable_recv_map.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/utils/mapUtils.js
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/timetable/ReceiveTestController.java

1. 검색기능 구현 -> 검색 결과 더 많이 뜨게 추후 수정해야 함
2. 타임테이블 합침/  병합 후 발생하는 에러 수정 중

1023 검색기능 구현, 타임테이블 합침, 병합 후 에러 수정 중 - 해진

---

Semi/WebContent/plan/timetable/timetable_basic.jsp
Semi/WebContent/plan/timetable/timetable_recv_map.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/utils/mapUtils.js
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/timetable/UpdateTimetableCotroller.java
Semi/src/dao/timetable/TimetableDao.java
Semi/src/dao/timetable/TimetableDaoImpl.java
Semi/src/dto/timetable/Location.java
Semi/src/service/timetable/TimetableService.java
Semi/src/service/timetable/TimetableServiceImpl.java

1. 드래그 앤 드롭 시 맵 좌표 변경 기능 구현
2. 저장 기능 구현 중

1023 - 맵 좌표 찍기 구현, 저장 기능 구현 중 - 해진

---

Semi/WebContent/plan/story/storyView.jsp
Semi/src/controller/story/StoryViewController.java
Semi/src/dao/story/StoryDao.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/dao/timetable/TimetableDao.java
Semi/src/dao/timetable/TimetableDaoImpl.java
Semi/src/dto/story/Story.java
Semi/src/dto/timetable/Timetable.java
Semi/src/service/timetable/TimetableServiceImpl.java

10/23
timetable 
dao , service : dto 추가한대로 수정했씀니당 plan으로 타임테이블리스트 불러오는 부분
dto: 장소이름, 일차, 스토리 유무 추가
storyView : ttblist 추가해서 전반적인 수정
- 상지

timetable dao 수정 service수정 dto추가, storyView ttblist 추가해서 전반적인 수정

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/story/storyView.jsp

1023 헤더 import 정리 - 해진

---

Semi/WebContent/layout/headerNoMenu.jsp
Semi/WebContent/main/main.jsp
Semi/WebContent/user/login.jsp
Semi/WebContent/user/myPage.jsp
Semi/WebContent/user/update.jsp
Semi/src/controller/user/SocialUserUpdateController.java
Semi/src/controller/user/UserDeleteController.java
Semi/src/controller/user/UserJoinController.java
Semi/src/controller/user/UserLoginController.java
Semi/src/controller/user/UserSocialLoginController.java
Semi/src/controller/user/UserUpdateController.java
Semi/src/dao/user/UserDaoImpl.java
Semi/src/filter/CacheControlFilter.java
Semi/src/service/user/UserServiceImpl.java

1. 세션문제때문에 CacheControlFilter라는 파일 추가
2. update.jsp에 회원탈퇴버튼에 기능 추가

1023화 지은 회원수정페이지

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/view.jsp

1023 헤더 include 임의 수정 - 해진

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/plan/PlanViewController.java
Semi/src/controller/timetable/ReceiveTestController.java
Semi/src/controller/timetable/UpdateTimetableCotroller.java
Semi/src/dao/timetable/TimetableDao.java
Semi/src/dao/timetable/TimetableDaoImpl.java
Semi/src/dto/timetable/Location.java
Semi/src/service/timetable/TimetableServiceImpl.java

1. 헤더 script 정리
2. 타임테이블 저장 구현 (우선적으로 개인 컨트롤러, UpdateTimetableController.java 생성해서 구현)
3. 타임테이블 view 구현 (PlanViewController 에 구현해놓음)

1024 - 타임테이블 저장, 불러오기 기능구현 - 해진

---

Semi/WebContent/inquiry/list.jsp
Semi/WebContent/inquiry/update.jsp
Semi/WebContent/inquiry/view.jsp
Semi/WebContent/inquiry/write.jsp
Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/notice/delete.jsp
Semi/WebContent/notice/list.jsp
Semi/WebContent/notice/update.jsp
Semi/WebContent/notice/write.jsp
Semi/WebContent/qna/delete.jsp
Semi/WebContent/qna/list.jsp
Semi/WebContent/qna/update.jsp
Semi/WebContent/qna/write.jsp
Semi/src/controller/Reply/ReplyInsertController.java
Semi/src/controller/inquiry/InqDeleteController.java
Semi/src/controller/inquiry/InqListController.java
Semi/src/controller/notice/NoticeListController.java
Semi/src/dao/board/NoticeDao.java
Semi/src/dao/board/NoticeDaoImpl.java
Semi/src/dao/board/ReplyDao.java
Semi/src/dao/board/ReplyDaoImpl.java
Semi/src/dto/user/User.java
Semi/src/service/board/AdminNoticeService.java
Semi/src/service/board/AdminNoticeServiceImpl.java
Semi/src/service/board/InquiryService.java
Semi/src/service/board/InquiryServiceImpl.java
Semi/src/service/board/NoticeService.java
Semi/src/service/board/NoticeServiceImpl.java

+ 2018.10.23 나영 이차로 한 일
- write에서 받아오는 값 변경
- 댓글 달면 답변 예정-> 답변 완료로 변경
- 사진은 한장만  올릴수 있게 구현 ... 
- 수정할때는 삭제해야지 새로운 사진 올릴 수 있음
- 리스트에서 답변 예정 색과 굵기 바꾸기
- list css 약간 수정 ?ㅋㅋㅋㅋ
- view css 약간의 수정ㅋㅋㅋㅋ
- write css 수정
- update css 수정
- header 수정 : 공지사항, Qna 링크 걸었어용
- qna, notice jsp 폴더 생성
- noticeService 약간의 수정

Dev/board 2018.10.24 나영

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/utils/mapUtils.js

1024 story 헤더에 <script >수정 - 해진

1024 story 헤더에 <script >수정 - 해진

---

Semi/WebContent/utils/mapUtils.js
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/plan/PlanViewController.java

<앞으로 할일>
1. 지도 좌표 일정 순서대로 연결시켜 찍어주기
2. 타임테이블 제목 누르면 모달 창(스토리 미니뷰) 띄우기
3. 일정 수정에서 날짜 수정하면, 타임테이블도 바로 적용되게 수정하기

1024 - 소소한 버그 수정들, 지표 좌표 찍어주는 부분 수정  - 해진

---

Semi/WebContent/plan/view.jsp
Semi/src/service/plan/PlanServiceImpl.java

1025 - 미니뷰 수정 - 해진

---

Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/plan/PlanUpdateController.java

1. 저장 버튼 누르면 플랜 정보와 타임테이블 둘다 저장되도록 변경
2. 플랜 수정모드에서 일정 정보 바꾸면 아래 타임테이블 날짜도 바뀜.
-> 기존 일정에 영향을 끼치면 경고창 띄우기 & 일정 삭제 기능 추가해야함

1024 - 저장 기능 합치기(플랜 정보 저장 + 타임테이블 저장), 날짜 바꾸면 타임테이블도 바꾸기 - 해진

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/view.jsp
Semi/src/service/stroy/StoryServiceImpl.java

10/25 
수정버튼 추가, 쓰기 ajax로 구현예정  delete 구현할 예정, SlidMenu 위치고정
- 상지

10/25 수정버튼 추가, delete 구현할 예정, SlidMenu 위치고정

---

Semi/WebContent/utils/mapUtils.js
Semi/src/controller/plan/PlanUpdateController.java
Semi/src/dao/timetable/TimetableDaoImpl.java
Semi/src/service/plan/PlanServiceImpl.java
Semi/src/service/timetable/TimetableServiceImpl.java

1025 - 소소한수정 하나 - 해진

---

Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp
Semi/WebContent/plan/view.jsp
Semi/src/controller/story/StoryDeleteController.java
Semi/src/controller/story/StoryUpdateController.java
Semi/src/controller/story/StoryViewController.java
Semi/src/controller/story/StoryWriteController.java
Semi/src/dao/main/MainDaoImpl.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/service/stroy/StoryServiceImpl.java

10/26
Syory Delete Update 구현됨, UI 수정
- 상지

10/26 STory Delete Update 구현됨, UI 수정

---

Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/view.jsp

10/26 타임테이블 z-index 수정

---

Semi/WebContent/contents/allContents.jsp
Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/main/main.jsp
Semi/src/controller/contents/AllContentsCtroller.java
Semi/src/dao/contents/ContentsDao.java
Semi/src/dao/contents/ContentsDaoImpl.java
Semi/src/dto/user/Search.java
Semi/src/service/contents/ContentsService.java
Semi/src/service/contents/ContentsServiceImpl.java
Semi/src/service/user/contentsService.java

1026금 지은 메인에 검색기능 추가

---

Semi/WebContent/admin/inquiry/inqView.jsp
Semi/WebContent/admin/notice/list.jsp
Semi/WebContent/admin/notice/view.jsp
Semi/WebContent/admin/notice/write.jsp
Semi/WebContent/inquiry/view.jsp
Semi/WebContent/inquiry/write.jsp
Semi/WebContent/notice/view.jsp
Semi/src/controller/admin/AdminNotiDeleteList.java
Semi/src/controller/admin/AdminNoticeDeleteController.java
Semi/src/controller/admin/AdminNoticeViewController.java
Semi/src/controller/admin/AdminNoticeWriteController.java
Semi/src/controller/admin/AdminQnaListController.java
Semi/src/controller/reply/ReplyInsertController.java
Semi/src/controller/user/UserLoginController.java
Semi/src/dao/board/NoticeDao.java
Semi/src/dao/board/NoticeDaoImpl.java
Semi/src/dao/board/NoticeFileDao.java
Semi/src/dao/board/NoticeFileDaoImpl.java
Semi/src/dao/board/QnaDao.java
Semi/src/dao/board/QnaDaoImpl.java
Semi/src/dao/board/QnaFileDao.java
Semi/src/dao/board/QnaFileDaoImpl.java
Semi/src/service/board/AdminNoticeService.java
Semi/src/service/board/AdminNoticeServiceImpl.java
Semi/src/service/board/AdminQnaService.java
Semi/src/service/board/AdminQnaServiceImpl.java
Semi/src/service/board/InquiryServiceImpl.java

- 사용자 inquiry view에서 댓글 다는 기능 없애기
- admin inquiry view에서 댓글 다는 기능 추가
- admin notice view 페이지 구혀어어언
- admin notice writer 구혀여여여넝
- admin notice update 구혀여엉ㄴ
2018.10.29 나영 학원에서 작업한 것
- admin QnA 시작쓰~
- list 구현중

2018.10.27 나영 집에서 한 일

---

Semi/src/dao/story/StoryDao.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/service/stroy/StoryService.java
Semi/src/service/stroy/StoryServiceImpl.java

스토리쪽 중복 메소드 삭제

---

Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/utils/mapUtils.js
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/plan/PlanUpdateController.java
Semi/src/controller/story/StoryMiniUpdateController.java
Semi/src/controller/story/StoryUpdateController.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/dao/timetable/TimetableDao.java
Semi/src/dao/timetable/TimetableDaoImpl.java
Semi/src/service/stroy/StoryService.java
Semi/src/service/stroy/StoryServiceImpl.java
Semi/src/service/timetable/TimetableService.java
Semi/src/service/timetable/TimetableServiceImpl.java

1030 - 미니뷰 수정 기능 구현중 - 해진

---

Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp
Semi/src/controller/story/StoryCommentWriteController.java
Semi/src/controller/story/StoryWriteController.java

10/30
storyWrite 
가계부쪽 UI수정,
가계부 저장 개발 ing~~~~
- 상지

10/30 가계부 개발중!!

---

Semi/src/controller/plan/PlanUpdateController.java

1030 - 테스트 중이던거 주석 처리 - 해진

---

Semi/WebContent/admin/plan/plist.jsp
Semi/WebContent/inquiry/list.jsp
Semi/WebContent/notice/list.jsp
Semi/WebContent/qna/list.jsp
Semi/src/controller/admin/AdminPlanListController.java
Semi/src/dao/board/InquiryDaoImpl.java
Semi/src/dao/board/NoticeDaoImpl.java
Semi/src/dao/board/QnaDaoImpl.java
Semi/src/dao/contents/ContentsDao.java
Semi/src/dao/contents/ContentsDaoImpl.java
Semi/src/dto/board/Inquiry.java
Semi/src/dto/board/Notice.java
Semi/src/dto/board/Qna.java
Semi/src/dto/plan/Plan.java
Semi/src/service/plan/AdminPlanService.java
Semi/src/service/plan/AdminPlanServiceImpl.java

- 게시글보기에서 게시글idx가 아닌 rnum 추가해서 으로 리스트 뽑기
- 게시판 DTO  수정 rnum 추가
- plan DTO에 nickname 추가
- plan 테스트 데이터 만들기
- plan 검색 list뽑기이이
- searchType  1 이면 제목 검색 , 2 는 닉네임

+ 2018.10.30 나영 작업

---

Semi/WebContent/plan/story/storyView.jsp

VIEW UI 수정중

---

Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp
Semi/src/controller/story/StoryUpdateController.java
Semi/src/controller/story/StoryViewController.java
Semi/src/controller/story/StoryWriteController.java
Semi/src/dao/account/AccountDao.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/dto/Account/Account.java
Semi/src/service/account/AccountServiceImpl.java

가계부쪽 숫자포멧 수정

---

Semi/WebContent/upload/myPage.jsp
Semi/WebContent/user/profileUpdate.jsp
Semi/WebContent/user/update.jsp
Semi/src/controller/user/UserFileController.java

마이페이지에 사진 클릭할때 form이 아니라 <a>로 연결

1031 지은 커밋

---

Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/view.jsp
Semi/src/controller/story/StoryViewController.java

10/31 accountList 수정 - 상지

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp

1031 - 탭 고정 기능 수정 - 해진

---

Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/user/myPage.jsp
Semi/WebContent/utils/mapUtils.js
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/plan/PlanViewController.java
Semi/src/controller/user/UserMypageController.java
Semi/src/dao/plan/PlanDao.java
Semi/src/dao/plan/PlanDaoImpl.java
Semi/src/dao/timetable/TimetableDaoImpl.java
Semi/src/dao/user/UserDao.java
Semi/src/dao/user/UserDaoImpl.java
Semi/src/dto/plan/Plan.java
Semi/src/dto/timetable/Location.java
Semi/src/dto/user/User.java
Semi/src/service/plan/PlanServiceImpl.java
Semi/src/service/user/UserService.java
Semi/src/service/user/UserServiceImpl.java

1. 총 여행거리 계산 구현 - 소수점 두자리까지 보여줌
- 여기서 유저(마이페이지)쪽 건듬
2. 날짜 헤더에 여행한 나라 이름 보여주기 구현

1101 - 여행거리계산, 나라이름 보여주기 구현 - 해진

---

Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp
Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/story/StoryDeleteController.java
Semi/src/controller/story/StoryMiniUpdateController.java
Semi/src/controller/story/StoryMiniViewController.java
Semi/src/controller/story/StoryUpdateController.java
Semi/src/controller/story/StoryWriteController.java
Semi/src/dao/account/AccountDaoImpl.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/dto/Account/Account.java
Semi/src/service/account/AccountService.java
Semi/src/service/account/AccountServiceImpl.java
Semi/src/service/stroy/StoryServiceImpl.java

11/1 
Stroy Account 구현 완료,(수시로 테스트해야되긴합니당....)
miniView Account UI 구현중
- 상지

11/1 miniView Account UI 구현

---

Semi/src/controller/plan/PlanCreateController.java
Semi/src/dto/plan/Plan.java

1101 - 머지 충돌났던거 수정 - 해진

---

Semi/WebContent/user/myPage.jsp

1. 총 개시물 수
2. 총 거리 띄워주는 곳 수정
받아오는 파라미터 명 변경

1101 - 소셜 로그인 마이페이지 쪽 수정 - 해진

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/user/myPage.jsp
Semi/WebContent/utils/timetableUtils.js
Semi/src/controller/plan/PlanWriteController.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/service/user/UserServiceImpl.java

1101 - 저장 활성화/비활성화 기능 구현 - 해진

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/main/main.jsp
Semi/WebContent/user/facebook.jsp
Semi/WebContent/user/myPage.jsp
Semi/src/controller/user/UserFileController.java
Semi/src/controller/user/UserMypageController.java
Semi/src/controller/user/UserUpdateController.java
Semi/src/dao/user/UserDaoImpl.java
Semi/src/service/user/UserServiceImpl.java

1. 헤더에서 '새일정' 버튼 누르면 모달창 뜨게 수정
2. 페이스북 로그인 구현!!!!!!!!ㅠ

1101목 지은 새일정 모달창, 페북 로긴

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp

1101 - 저장 동작 소소한 버그 수정 - 해진

---

Semi/WebContent/contents/allContents.jsp
Semi/WebContent/contents/newContents.jsp
Semi/WebContent/layout/headerWithMenu.jsp
Semi/src/controller/contents/AllContentsCtroller.java
Semi/src/controller/contents/NewContentsController.java
Semi/src/controller/contents/RecommContentsController.java
Semi/src/dao/plan/PlanDao.java
Semi/src/dao/plan/PlanDaoImpl.java
Semi/src/service/contents/ContentsService.java
Semi/src/service/contents/ContentsServiceImpl.java

+201811.01 나영

---

Semi/src/controller/story/StoryViewController.java

11/2story쪽 class 손보는중!

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/write.jsp

1102 - 새일정 만들기 버그 수정 - 해진

---

Semi/WebContent/plan/write.jsp
Semi/WebContent/utils/timetableUtils.js

1102 - 저장버튼 관련 버그 수정 - 해진

---

Semi/WebContent/plan/write.jsp

1102 - 읽기 모드로 변경하는 버튼 구현 - 해진

---

Semi/WebContent/plan/story/storyCommentView.jsp
Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp
Semi/src/controller/story/StoryUpdateController.java
Semi/src/controller/story/StoryWriteController.java

11/02 story css 빼는중입니당!!

---

Semi/src/controller/bookmark/BookmarkDeleteController.java
Semi/src/controller/bookmark/BookmarkInsertController.java

dev/plan 18/11/01

---

Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/WebContent/plan/write.jsp

11/02 가계부 오류 수정-상지

---

Semi/WebContent/resources/planCommStyle.css

1102 - 타임테이블 오늘자 하이라이트 기능 삭제 - 해진

---

Semi/WebContent/plan/timetable/miniViewWrite.jsp

11/02 miniView account 수정

---

Semi/src/dao/user/UserDaoImpl.java

11/02 userDao 수정

---

Semi/WebContent/plan/story/storyCommentView.jsp
Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp

11/05 
스토리부분 널값 오류 수정, 
스토리 없을때, 장소이름 위에 시작시간값 나오게 바꿈, 
소소한 오류 수정
- 상지 -

11/05 스토리부분 널값 오류 수정, 스토리 없을때, 장소이름 위에 시작시간값 나오게 바꿈, 소소한 오류 수정 -상지

---

Semi/WebContent/plan/story/storyView.jsp
Semi/src/controller/story/StoryUpdateController.java

11/05 깃헙이 나에게똥을줬어요 흑흑 이건되겟지?

---

Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/WebContent/plan/write.jsp
Semi/src/controller/plan/PlanUpdateController.java
Semi/src/dao/account/AccountDao.java
Semi/src/dao/account/AccountDaoImpl.java
Semi/src/service/account/AccountService.java
Semi/src/service/account/AccountServiceImpl.java
Semi/src/service/timetable/TimetableService.java
Semi/src/service/timetable/TimetableServiceImpl.java

1105 - 타임테이블 삭제와 동시에 가계부 적용 - 해진

---

Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp

11/05 스토리 CSS 적용ing 갈수록 이상해지고 있어요ㅜㅜ -상지

11/05 스토리 CSS 적용ing 갈수록 이상해지고 있어요ㅜㅜ

---

Semi/WebContent/plan/view.jsp

1105 - 가계부 '원' 글자 추가 - 해진

---

Semi/src/controller/plan/PlanUpdateController.java
Semi/src/dao/account/AccountDaoImpl.java
Semi/src/service/timetable/TimetableService.java
Semi/src/service/timetable/TimetableServiceImpl.java

1105 - 가계부 삭제 버그 수정 - 해진

---

Semi/WebContent/resources/planCommStyle.css

1105 - footer CSS 문제 해결 - 해진

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css

dev/plan 18/11/05

---

Semi/WebContent/plan/timetable/miniView.jsp
Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css

1105 - CSS 수정중

---

Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp
Semi/WebContent/plan/write.jsp

11/05 CSS 작업 

---

Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp

11/06 
스토리 css 작업, 스토리쪽 가계부 콤마 작업완료
미니뷰쪽은 아직 안건드렸어용
- 상지 -

11/06 스토리 css 작업, 스토리쪽 가계부 콤마 작업완료 -상지-

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css

1. 배너사진변경버튼 -> span으로 변경
2. view.jsp, write.jsp 아이콘색상 변경
3. 그래프 버튼 -> span으로 변경
4. 기타 짤짤이

dev/plan 18/11/06

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css

1106 - 플랜쪽 css 수정 -해진

---

Semi/WebContent/plan/view.jsp
Semi/src/controller/plan/PlanViewController.java

1106 - 가계부 css추가 수정 - 해진

---

Semi/WebContent/plan/timetable/miniView.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css

1106 - 배너 사진 로컬에서만 변경(DB 즉시 저장x) -해진

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/resources/planCommStyle.css

1106 - 배너 css 뷰쪽 재 수정 -해진

---

Semi/WebContent/plan/story/storyCommentView.jsp
Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/timetable/miniView.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp

storyAccount 콤마수정완료! plan 정보 css중 -상지

11/06 storyAccount 콤마수정완료! plan 정보 css중-상지

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/resources/planCommStyle.css

1106 - 플랜 뷰 배너 css 수정 - 해진

---

Semi/WebContent/layout/footer.jsp

2018.11.06 나영

---

Semi/WebContent/plan/write.jsp

1106 write.jsp planInfo정보 css완료 -상지

1106 write.jsp planInfo정보 css완료 -상지

---

Semi/WebContent/plan/view.jsp

계부 띄워줄 때 화폐단위로 , 찍어주기/ css 간격수정

1106 - 가계부 띄워줄 때 화폐단위로 , 찍어주기/ css 간격수정  -해진

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/story/storyView.jsp

1106 컨텐츠 메뉴 css 수정-상지

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/user/myPage.jsp
Semi/src/controller/plan/PlanAccountViewController.java
Semi/src/controller/plan/PlanViewController.java
Semi/src/dao/plan/PlanDao.java
Semi/src/dao/plan/PlanDaoImpl.java
Semi/src/service/plan/PlanService.java
Semi/src/service/plan/PlanServiceImpl.java

마이페이지 css 수정/ 일정보기 - 가계부 타입, css수정

1106 - 마이페이지 css 수정/ 일정보기 - 가계부 타입, css수정 -해진

---

Semi/src/dao/user/UserDaoImpl.java

+ 2018.11.06 나영

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css

1106 - 플랜 수정 배너 css, 비번 찾기 css  - 해진

---

Semi/WebContent/plan/write.jsp
Semi/src/controller/plan/PlanUpdateController.java

1106 css 수정

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css

1106 - 북마크 css 수정 -해진

---

Semi/src/dao/plan/PlanDaoImpl.java

dev/plan 18/11/07

---

Semi/WebContent/plan/story/storyView.jsp
Semi/src/dao/story/StoryDaoImpl.java

1107 오류수정(스토리) - 상지

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css
Semi/src/controller/plan/PlanAccountViewController.java
Semi/src/controller/plan/PlanViewController.java
Semi/src/controller/story/StoryMiniUpdateController.java
Semi/src/controller/story/StoryMiniViewController.java
Semi/src/dao/plan/PlanDao.java
Semi/src/dao/plan/PlanDaoImpl.java
Semi/src/service/plan/PlanService.java
Semi/src/service/plan/PlanServiceImpl.java
Semi/src/service/timetable/TimetableServiceImpl.java

가계부 단위 double -> long 형으로 변경/ 소소한 css 수정들

1107 - 가계부 단위 double -> long 형으로 변경/ 소소한 css 수정들 - 해진

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/main/main.jsp
Semi/src/controller/plan/PlanCreateController.java
Semi/src/controller/plan/PlanWriteController.java
Semi/src/dao/plan/PlanDao.java
Semi/src/dao/plan/PlanDaoImpl.java
Semi/src/dto/plan/Plan.java
Semi/src/service/plan/PlanService.java
Semi/src/service/plan/PlanServiceImpl.java

1. 새일정만들기 에서 예외 처리
2. 새일정 만든후 새로고침하면 같은 이름으로 또 새로운 일정 만들어지는 오류 수정
3. css 몇개 수정..(기억안남)

1107수 지은 커밋 - 자잘한 오류들 수정

---

Semi/WebContent/contents/allContents.jsp

11/07 모든컨텐츠 오류수정 - 상지

---

Semi/WebContent/plan/timetable/miniView.jsp
Semi/WebContent/plan/view.jsp

1107 - 미니뷰 수정 한것 - 해진

---

Semi/WebContent/plan/write.jsp
Semi/WebContent/resources/planCommStyle.css

1107 - 배너아이콘 위치 수정 - 해진

---

Semi/WebContent/plan/story/storyUpdate.jsp
Semi/WebContent/plan/story/storyWrite.jsp
Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/WebContent/plan/write.jsp

1107 - 한글 입력방지 수정1 - 상지

---

Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/timetable/miniViewWrite.jsp
Semi/src/controller/story/StoryUpdateController.java

11/08 story 가계부한글입력시 오류 수정, 스토리 업데이트시 오류 수정 -상지

11/08 story 가계부한글입력시 오류 수정, 스토리 업데이트시 오류 수정

---

Semi/WebContent/plan/view.jsp
Semi/WebContent/utils/mapUtils.js
Semi/WebContent/utils/timetableUtils.js
Semi/src/service/timetable/TimetableServiceImpl.java

1108 - 타임테이블 버그 수정 - 해진

---

Semi/WebContent/plan/view.jsp

dev/plan 18/11/08

---

Semi/WebContent/plan/timetable/miniView.jsp
Semi/WebContent/user/myPage.jsp
Semi/WebContent/utils/mapUtils.js

1108 - 마이페이지 css 수정 중  -해진

---

Semi/WebContent/plan/write.jsp
Semi/WebContent/user/myPage.jsp
Semi/WebContent/utils/timetableUtils.js

1108 - 일정 날짜 수정 버그 고침 - 해진

---

Semi/WebContent/admin/user/userList.jsp
Semi/WebContent/contents/allContents.jsp
Semi/src/dao/user/UserDaoImpl.java

contents all -> 관리자 페이지로 가는거 수정
userList -> 회원 탈퇴 보여주기

+ 2018.11.08 나영

---

Semi/WebContent/plan/story/storyView.jsp
Semi/WebContent/plan/story/storyWrite.jsp
Semi/planUML.ucls
Semi/src/controller/story/StoryImageDeleteController.java
Semi/src/utils/DBConn.java
Semi/storyUML.ucls

11/08 주석추가 UML 추가 DBConn지은언니껄로 바꿨음!

11/08 주석추가 UML 추가 DBConn지은언니껄로 바꿨음!

---

Semi/WebContent/plan/write.jsp
Semi/WebContent/utils/timetableUtils.js

1108 - 날짜 변경 버그 고침 - 해진

---

Semi/WebContent/layout/headerWithMenu.jsp
Semi/WebContent/plan/view.jsp
Semi/WebContent/plan/write.jsp
Semi/WebContent/utils/timetableUtils.js

1108 - 탭 변경 버그 수정 - 해진

---

Semi/WebContent/admin/comment/clist.jsp
Semi/WebContent/layout/headerNoMenu.jsp
Semi/src/controller/contents/AllContentsCtroller.java
Semi/src/utils/DBConn.java

+2018.11.08 나영

---

Semi/WebContent/plan/story/storyCommentView.jsp

11/08 관리자 댓글관리 삭제 기능 다시 수정!! -상지

11/08 관리자 댓글관리 삭제 기능 다시 수정!! -상지

---

Semi/src/controller/admin/AdminCommentListController.java
Semi/src/dao/story/StoryDaoImpl.java
Semi/src/service/stroy/AdminStoryServiceImpl.java

+ 2018.11.09 나영

---

Semi/WebContent/admin/comment/clist.jsp
Semi/WebContent/admin/notice/list.jsp
Semi/WebContent/resources/planCommStyle.css

181109 금요일 날씨 좋음 최종 머지~!!!!!!!

---

Semi/WebContent/main/main.jsp

1109 - 최종 커밋 - 해진
